apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  # Under labels when can add arbitrary values as we wish to tag/label/describe our POD for easier filtering later
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx