apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-hello-nginx
  labels:
    app: hello-nginx
    type: front-end
spec:
  template:
    # Basically copy-paste from pod-hello-nginx.yml
    # This is the template of the POD, so that ReplicationController knows how to create new PODS when needed
    metadata:
      name: hello-nginx-pod
      labels:
        app: hello-nginx
        type: front-end
    spec:
      containers:
        - name: hello-nginx-container
          image: nginx
  # How many PODs / replicas we want to maintain always
  replicas: 3