apiVersion: v1
kind: Pod
metadata:
  name: pod-hello-nginx
  # Under labels when can add arbitrary values as we wish to tag/label/describe our POD for easier filtering later
  labels:
    app: hello-nginx
    type: front-end
spec:
  containers:
    - name: hello-nginx-container
      image: nginx