apiVersion: v1
kind: Pod
metadata:
  name: pod-hello-postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: hello-postgres-container
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword